### PR TITLE
Allow configuring ip tracking by loading columns from bff API

### LINKED ISSUE #164: Remove "Last IP" column
Due to GDPR-related concerns, we would like to be able to disable the "Last IP" column or get rid of it altogether.

### PR DESCRIPTION
**Pull request by b-rowan**
IP tracking can now be disabled with the `track_device_ip` config flag. The UI also has to hide this column, as it will no longer show up in data. To handle this, the table columns are dynamically created with a request to the bff API.

Fixes #164

### CODE REVIEW

**Comment by b-rowan** [comment]
I would like to extend this style of creating tables dynamically from the BFF API, as it allows us to extend them in the future, including allowing users to configure what columns should be shown, which can reduce clutter.

**Review by easybe — CHANGES_REQUESTED** [review]
I tried it (on top of current master), and, "Online/Last seen" no longer seems to work.

**Review by easybe — APPROVED** [review]
Works again, thanks!

**Comment by easybe** [comment]
> I would like to extend this style of creating tables dynamically from the BFF API, as it allows us to extend them in the future, including allowing users to configure what columns should be shown, which can reduce clutter.
> 
> Let me know thoughts on this. If we want to go in this direction I will do this for the other pages as well.

I don't have an opinion on this. But, maybe @tsagadar has one.

**Pull request merged**
