### PR TITLE
Remove IP tracking

### PR DESCRIPTION
**Pull request by b-rowan**
Fixes: #164

### CODE REVIEW

**Review by easybe — CHANGES_REQUESTED** [review]
Please use a meaningful name for the migration, e.g. `1_20241019081940_drop_last_ip.py`

LGTM otherwise

**Comment by jameshilliard** [comment]
I'm thinking it's better to make this a config flag to disable rather than remove the columns entirely.

**Review by easybe — APPROVED** [review]

**Comment by easybe** [comment]
> I'm thinking it's better to make this a config flag to disable rather than remove the columns entirely.

Both is fine for us. However, I guess this can easily be brought back when needed. Anyway, IMHO we should focus on getting the core functionality as stable/usable as possible, so less is more. For us, the most important thing is scalability, as we have a lot of devices.

**Comment by b-rowan** [comment]
I think based on recent discussion that this should be reworked to a config option.  Should be pretty simple, it will only instantiate the middleware if the config flag is enabled.

**Pull request closed without merging**
