### PR TITLE
Update python for tests/pages and add poetry lockfile

### PR DESCRIPTION
**Pull request by jameshilliard**
I think it's generally considered best practices to commit the lockfile for projects like this.

### CODE REVIEW

**Review by b-rowan — APPROVED** [review]

**Comment by b-rowan** [comment]
Maybe disable the poetry actions on CI?

**Comment by jameshilliard** [comment]
That's a strange error:
```
Failed to resolve 'pypi.org'
```

**Comment by jameshilliard** [comment]
> Maybe disable the poetry actions on CI?

Disabled the lock action and got it working.

**Comment by b-rowan** [comment]
> > Maybe disable the poetry actions on CI?
> 
> Disabled the lock action and got it working.

If it works when you push it though, then it just needs to be disabled in pre-commit-ci

**Pull request merged**
